"""
Candidate supply-side reforms California could plausibly enact without a
constitutional amendment. Source-of-truth list-of-dicts; export to CSV.

Scoring: 1-5 (5 = most positive on that dimension; for risk/complexity scores,
5 = highest difficulty/risk).

Categories:
  zoning, permitting, ceqa, fees_finance, building_code, infrastructure_utilities,
  commercial_smb, labor_delivery, fiscal_capture, anti_sabotage
"""

from __future__ import annotations
from typing import List, Dict
import csv
from pathlib import Path


REFORMS: List[Dict] = [
    {
        "reform_name": "State multifamily zoning floor in urbanized areas",
        "category": "zoning",
        "description": "Mandate by-right multifamily on all parcels >=4,000 sqft within 0.5 mi of frequent transit, employment centers, and commercial corridors; floor binds notwithstanding charter-city home rule.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 5,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 4,
        "political_difficulty_score": 5,
        "time_to_material_impact": "3-6 yrs",
        "primary_constraint_addressed": "legal_capacity",
        "include_in_maximum_scenario": True,
        "notes": "Statewide-concern doctrine sustains; SB 9/SB 35/SB 423 precedent. Charter cities have lost similar challenges (CHF v. Berkeley, Bldg Industry v. SF).",
    },
    {
        "reform_name": "Missing-middle by-right (4-12 unit buildings on residential parcels)",
        "category": "zoning",
        "description": "Allow fourplexes, sixplexes, cottage courts, townhomes, and small apartment buildings on parcels currently zoned R-1 or R-2 in urbanized areas, subject to objective standards.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 4,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 3,
        "political_difficulty_score": 5,
        "time_to_material_impact": "3-7 yrs",
        "primary_constraint_addressed": "legal_capacity",
        "include_in_maximum_scenario": True,
        "notes": "SB 9 narrow precedent. Auckland and Minneapolis comparators show modest but real production gains over 5-10 yrs.",
    },
    {
        "reform_name": "Office/retail-to-residential by-right conversions",
        "category": "zoning",
        "description": "Statewide ministerial approval for adaptive reuse of obsolete office, retail, hotel, and parking sites to residential, with objective standards on egress/seismic/fire only.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 4,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "legal_capacity",
        "include_in_maximum_scenario": True,
        "notes": "AB 2011/AB 1633 trajectory. Cost economics depend on building geometry; not a silver bullet. Evidence: medium.",
    },
    {
        "reform_name": "Religious and institutional land housing-by-right",
        "category": "zoning",
        "description": "Allow housing on land owned by religious institutions, hospitals, universities, and nonprofits by right under objective standards (SB 4 expansion).",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 2,
        "litigation_risk_score": 2,
        "political_difficulty_score": 2,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "legal_capacity",
        "include_in_maximum_scenario": True,
        "notes": "SB 4 (Wiener) precedent already in force. Medium impact ceiling but politically tractable.",
    },
    {
        "reform_name": "Public-land housing fast-track (school, parks, surplus)",
        "category": "zoning",
        "description": "All surplus public land in urbanized areas presumptively available for housing, with state Office of Land Use empowered to override local objections to specific parcels.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "3-6 yrs",
        "primary_constraint_addressed": "legal_capacity",
        "include_in_maximum_scenario": True,
        "notes": "Surplus Land Act extension. School-district land is politically thorny (Prop 39 history).",
    },
    {
        "reform_name": "SB 79 transit-oriented density as floor not ceiling",
        "category": "zoning",
        "description": "Treat SB 79 TOD densities as floors that local governments cannot reduce; pre-empt local downzonings and overlay restrictions within station areas.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 4,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 2,
        "litigation_risk_score": 3,
        "political_difficulty_score": 4,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "legal_capacity",
        "include_in_maximum_scenario": True,
        "notes": "SB 79 already enacted. The floor-not-ceiling framing is the binding question.",
    },
    {
        "reform_name": "Ministerial approval with strict shot clocks and deemed-approved",
        "category": "permitting",
        "description": "60-day shot clock for ministerial review of qualifying projects; missed deadline = automatic approval. State backstop for repeated violations.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 5,
        "commercial_impact_score": 4,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "1-3 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": True,
        "notes": "Permit Streamlining Act extension. SB 35/423 model. Strong evidence base.",
    },
    {
        "reform_name": "Objective standards mandate for all residential review",
        "category": "permitting",
        "description": "Bar discretionary design review, subjective neighborhood compatibility findings, and aesthetic veto for residential projects meeting objective standards.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 4,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "2-4 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": True,
        "notes": "Housing Accountability Act expansion. Empirical base: strong.",
    },
    {
        "reform_name": "State permitting backstop office",
        "category": "permitting",
        "description": "New state Office of Housing Approval with authority to issue binding approvals when local agencies miss deadlines, apply invalid standards, or repeatedly violate state law; escalating fines and deemed approvals.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 5,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 5,
        "litigation_risk_score": 3,
        "political_difficulty_score": 4,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "anti_sabotage",
        "include_in_maximum_scenario": True,
        "notes": "Critical to making preemption real. Will be litigated; Sole-state-concern doctrine should hold.",
    },
    {
        "reform_name": "CEQA exemption for infill housing and adaptive reuse",
        "category": "ceqa",
        "description": "Statutory CEQA exemption for infill housing, mixed-use infill, and adaptive reuse meeting objective standards; preserves federal NEPA, Coastal Act, tribal consultation, and seismic/hazmat rules.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 4,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 2,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "1-3 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": True,
        "notes": "AB 130/SB 131 baseline trajectory. Single most impactful CEQA reform per project.",
    },
    {
        "reform_name": "CEQA exemption for energy/grid/water/transit infrastructure",
        "category": "ceqa",
        "description": "Categorical CEQA exemption for grid upgrades, transformer/substation installs, water/sewer rehab, bus-priority lanes, active transportation, and energy storage.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "infrastructure",
        "include_in_maximum_scenario": True,
        "notes": "Necessary corollary to housing reforms. Bus-priority CEQA reform already partially enacted (SB 922).",
    },
    {
        "reform_name": "Anti-CEQA-abuse: mandatory loser-pays in non-environmental CEQA suits",
        "category": "ceqa",
        "description": "Where CEQA litigation is brought primarily for non-environmental purposes (NIMBY blocking, labor leverage), losing plaintiff pays defendant fees.",
        "legal_plausibility_score": 3,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 4,
        "political_difficulty_score": 5,
        "time_to_material_impact": "2-4 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": False,
        "notes": "Politically toxic. Excluded from central scenario; useful only if courts uphold a narrower abuse standard.",
    },
    {
        "reform_name": "Standardized statewide impact-fee schedule with nexus caps",
        "category": "fees_finance",
        "description": "Cap impact fees at percent of project value or at evidentiary nexus, whichever is lower; require transparent fee schedules; no late-stage surprise fees.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "2-4 yrs",
        "primary_constraint_addressed": "construction_cost",
        "include_in_maximum_scenario": True,
        "notes": "AB 602 baseline. Real but second-order impact.",
    },
    {
        "reform_name": "Inclusionary feasibility floor",
        "category": "fees_finance",
        "description": "Cap inclusionary requirements at level shown by feasibility study to not block production; if local inclusionary kills feasibility, state defaults to lower percentage.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 3,
        "political_difficulty_score": 5,
        "time_to_material_impact": "3-5 yrs",
        "primary_constraint_addressed": "financing",
        "include_in_maximum_scenario": False,
        "notes": "Affordable-housing politics. Useful but excluded from central to keep coalition.",
    },
    {
        "reform_name": "EIFD/IFD/CRIA expansion + state matching grants",
        "category": "fiscal_capture",
        "description": "Expand Enhanced Infrastructure Financing Districts and similar tools; state matches local infrastructure bonds in growth corridors; LA-share property tax increment can fund growth-enabling infrastructure.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 1,
        "political_difficulty_score": 3,
        "time_to_material_impact": "3-7 yrs",
        "primary_constraint_addressed": "fiscal_capture",
        "include_in_maximum_scenario": True,
        "notes": "Post-redevelopment fiscal plumbing fix. Without it, growth dividend leaks.",
    },
    {
        "reform_name": "Single-stair / point-access-block reform",
        "category": "building_code",
        "description": "Allow single-stair multifamily up to 6 stories with sprinklers and modern egress, harmonized statewide.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "construction_cost",
        "include_in_maximum_scenario": True,
        "notes": "Seattle, Honolulu, Vancouver have done it. Modest cost reduction; widens feasibility envelope on small lots.",
    },
    {
        "reform_name": "Modular and factory-built housing fast-track approvals",
        "category": "building_code",
        "description": "Statewide approval body for modular/factory-built housing types; pre-approved plans valid in any jurisdiction.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "3-6 yrs",
        "primary_constraint_addressed": "construction_cost",
        "include_in_maximum_scenario": True,
        "notes": "HCD already does some of this. Bigger upside if combined with construction-defect liability reform.",
    },
    {
        "reform_name": "Statewide pattern-book multifamily designs",
        "category": "building_code",
        "description": "Pre-approved multifamily building designs (3-, 4-, 6-plex, courtyard apartments) with standardized engineering; locals must accept by-right.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 0,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "construction_cost",
        "include_in_maximum_scenario": True,
        "notes": "Reduces architecture/engineering cost on small projects substantially.",
    },
    {
        "reform_name": "Construction-defect liability reform for condos",
        "category": "building_code",
        "description": "Cap statute of limitations and tort exposure on multifamily condo construction defects to make condo construction insurable again.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 0,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 3,
        "political_difficulty_score": 5,
        "time_to_material_impact": "3-7 yrs",
        "primary_constraint_addressed": "financing",
        "include_in_maximum_scenario": True,
        "notes": "Plaintiffs bar opposition is intense. Without this, condo construction stays near zero.",
    },
    {
        "reform_name": "Parking minimum elimination near transit and corridors",
        "category": "zoning",
        "description": "AB 2097 expansion: zero parking minimums on parcels within 0.5 mi of transit OR commercial corridors OR jobs centers; no de facto parking requirements via traffic study.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 4,
        "implementation_complexity_score": 1,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "1-3 yrs",
        "primary_constraint_addressed": "construction_cost",
        "include_in_maximum_scenario": True,
        "notes": "AB 2097 already does much of this. High leverage per unit cost.",
    },
    {
        "reform_name": "LADWP/SCE/SoCalGas interconnection shot clock",
        "category": "infrastructure_utilities",
        "description": "60-day plan review and 120-day energization SLA for new multifamily; missed deadline = deemed-energized for occupancy purposes; CPUC enforcement; transparent capacity maps.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 4,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 5,
        "litigation_risk_score": 3,
        "political_difficulty_score": 4,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "utilities",
        "include_in_maximum_scenario": True,
        "notes": "LADWP is municipal; legal mechanism differs (state utility regulation + LA charter). Most leveraged single utility reform.",
    },
    {
        "reform_name": "State transformer procurement pool",
        "category": "infrastructure_utilities",
        "description": "State acts as group buyer/standardization body for distribution transformers; bulk-purchase contracts and stockpile reduce 18+ month lead times.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "2-4 yrs",
        "primary_constraint_addressed": "utilities",
        "include_in_maximum_scenario": True,
        "notes": "Federal IRA funding leverage. Direct binding constraint.",
    },
    {
        "reform_name": "Coordinated trenching mandate (dig-once)",
        "category": "infrastructure_utilities",
        "description": "Mandate joint trenching for water/sewer/electric/fiber in any street project; reduces serial outages and per-unit infrastructure cost.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 2,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "3-7 yrs",
        "primary_constraint_addressed": "infrastructure",
        "include_in_maximum_scenario": True,
        "notes": "Cost savings reinvest into capacity.",
    },
    {
        "reform_name": "Pre-approved electrification packages for multifamily",
        "category": "infrastructure_utilities",
        "description": "Standardized electrical-service designs for common multifamily building types accepted by all utilities without bespoke plan review.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 2,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 2,
        "litigation_risk_score": 1,
        "political_difficulty_score": 1,
        "time_to_material_impact": "1-3 yrs",
        "primary_constraint_addressed": "utilities",
        "include_in_maximum_scenario": True,
        "notes": "Quick win.",
    },
    {
        "reform_name": "Restaurants/cafes/clinics by-right in commercial zones",
        "category": "commercial_smb",
        "description": "Restaurants, cafes, bars, gyms, clinics, childcare, and small venues by-right in commercial and mixed-use zones, subject to objective health/fire/noise standards. CUP abuse limited.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 1,
        "commercial_impact_score": 5,
        "implementation_complexity_score": 2,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "1-3 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": True,
        "notes": "Empirically weaker evidence base than housing reform — flag as medium-confidence.",
    },
    {
        "reform_name": "Outdoor dining and small-venue by-right",
        "category": "commercial_smb",
        "description": "COVID-era outdoor dining permits made permanent statewide; small entertainment venues operable under objective noise/safety/operating-hours standards.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 0,
        "commercial_impact_score": 4,
        "implementation_complexity_score": 1,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "1-2 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": True,
        "notes": "Politically popular. Real but modest impact.",
    },
    {
        "reform_name": "Standardized statewide health/fire/building signoffs",
        "category": "commercial_smb",
        "description": "Single statewide form and timeline for tenant-improvement health/fire/building signoffs; eliminates duplicative city-county approval chains.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 1,
        "commercial_impact_score": 4,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 2,
        "political_difficulty_score": 3,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": True,
        "notes": "Legal collision risk: county health departments will resist.",
    },
    {
        "reform_name": "CUP-abuse limit and formula-retail-ban preemption",
        "category": "commercial_smb",
        "description": "Limit conditional use permits as a discretionary commercial veto where state economic development policy is impaired; preempt formula-retail bans that conflict with statewide policy.",
        "legal_plausibility_score": 3,
        "housing_supply_impact_score": 0,
        "commercial_impact_score": 3,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 4,
        "political_difficulty_score": 4,
        "time_to_material_impact": "3-6 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": False,
        "notes": "Charter-city / 1st amendment / local merchant politics. Excluded from central scenario.",
    },
    {
        "reform_name": "State permitting surge teams and building-dept staffing grants",
        "category": "labor_delivery",
        "description": "State pays for additional plan checkers, inspectors, and permit staff in jurisdictions with permit-velocity below threshold; surge teams deployable for backlog reduction.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 1,
        "political_difficulty_score": 1,
        "time_to_material_impact": "1-3 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": True,
        "notes": "Cheap, fast, popular. Underrated reform.",
    },
    {
        "reform_name": "Construction trades workforce expansion",
        "category": "labor_delivery",
        "description": "Apprenticeship pipeline expansion for electricians, plumbers, elevator techs, inspectors, and utility crews; coordinated with community colleges and unions.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 1,
        "political_difficulty_score": 2,
        "time_to_material_impact": "5-10 yrs",
        "primary_constraint_addressed": "construction_cost",
        "include_in_maximum_scenario": True,
        "notes": "Long lead time; labor capacity caps everything.",
    },
    {
        "reform_name": "Public infrastructure design-build authority",
        "category": "labor_delivery",
        "description": "Permanent design-build authority for housing-enabling infrastructure (utilities, transit, streets); standardized P3 templates.",
        "legal_plausibility_score": 5,
        "housing_supply_impact_score": 2,
        "commercial_impact_score": 2,
        "implementation_complexity_score": 3,
        "litigation_risk_score": 1,
        "political_difficulty_score": 3,
        "time_to_material_impact": "2-5 yrs",
        "primary_constraint_addressed": "infrastructure",
        "include_in_maximum_scenario": True,
        "notes": "Procurement reform yields material time savings.",
    },
    {
        "reform_name": "Anti-sabotage compliance audit and penalty regime",
        "category": "anti_sabotage",
        "description": "HCD authorized to audit local approval records; jurisdictions with documented sabotage face escalating fines and Builder's Remedy expansion.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 3,
        "political_difficulty_score": 4,
        "time_to_material_impact": "3-6 yrs",
        "primary_constraint_addressed": "anti_sabotage",
        "include_in_maximum_scenario": True,
        "notes": "Necessary teeth; without it, cities comply on paper and obstruct in practice.",
    },
    {
        "reform_name": "Coastal Act delegation reform for non-shoreline parcels",
        "category": "ceqa",
        "description": "Clarify Coastal Act jurisdiction so parcels beyond direct shoreline impact are not subject to Coastal Commission appeal; preserve genuine coastal protection.",
        "legal_plausibility_score": 3,
        "housing_supply_impact_score": 2,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 4,
        "political_difficulty_score": 5,
        "time_to_material_impact": "5-10 yrs",
        "primary_constraint_addressed": "approvals",
        "include_in_maximum_scenario": False,
        "notes": "Coastal Commission constitutionally protected; reform is hard. Excluded from central.",
    },
    {
        "reform_name": "Insurance-market backstop for new multifamily",
        "category": "fees_finance",
        "description": "State reinsurance pool for builder's risk and condo construction insurance to reduce capital-market risk on new construction.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 3,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 4,
        "litigation_risk_score": 1,
        "political_difficulty_score": 3,
        "time_to_material_impact": "3-6 yrs",
        "primary_constraint_addressed": "financing",
        "include_in_maximum_scenario": False,
        "notes": "Promising but new mechanism. Watch as separate track.",
    },
    {
        "reform_name": "Property-tax allocation reform for growth",
        "category": "fiscal_capture",
        "description": "Within Prop 13 1% cap, modify ERAF and post-1992 allocation rules so growth-impacted jurisdictions receive a larger share of new construction property tax — reduces fiscal misalignment.",
        "legal_plausibility_score": 4,
        "housing_supply_impact_score": 2,
        "commercial_impact_score": 1,
        "implementation_complexity_score": 5,
        "litigation_risk_score": 3,
        "political_difficulty_score": 5,
        "time_to_material_impact": "5-10 yrs",
        "primary_constraint_addressed": "fiscal_capture",
        "include_in_maximum_scenario": False,
        "notes": "Schools coalition opposition. Excluded from central; included only if politics shift.",
    },
]


def reforms_to_csv(path):
    """Write reforms to CSV with stable column order."""
    columns = [
        "reform_name", "category", "description",
        "legal_plausibility_score", "housing_supply_impact_score",
        "commercial_impact_score", "implementation_complexity_score",
        "litigation_risk_score", "political_difficulty_score",
        "time_to_material_impact", "primary_constraint_addressed",
        "include_in_maximum_scenario", "notes",
    ]
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=columns)
        writer.writeheader()
        for r in REFORMS:
            row = {k: r[k] for k in columns}
            writer.writerow(row)


def top_n_by_combined_score(n: int = 10):
    """Rank by housing+commercial impact - difficulty."""
    def score(r):
        return (
            r["housing_supply_impact_score"] * 1.0
            + r["commercial_impact_score"] * 0.5
            + r["legal_plausibility_score"] * 0.7
            - r["litigation_risk_score"] * 0.4
            - r["implementation_complexity_score"] * 0.3
            - r["political_difficulty_score"] * 0.4
        )
    ranked = sorted(REFORMS, key=score, reverse=True)
    return ranked[:n]


if __name__ == "__main__":
    reforms_to_csv(Path(__file__).parent.parent / "outputs" / "reform_menu.csv")
    print(f"{len(REFORMS)} reforms written.")
    print("Top 10 by combined score:")
    for r in top_n_by_combined_score(10):
        print(f"  - {r['reform_name']} [{r['category']}]")
